name: Node CI

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - stable*

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [12.x, 15.x]

    steps:
    - uses: actions/checkout@v1
    - uses: c-hive/gha-npm-cache@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm ci
    - name: npm build
      run: npm run build
